version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cryptotrading-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - cryptotrading-network

  redis:
    image: redis:7-alpine
    container_name: cryptotrading-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cryptotrading-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: cryptotrading-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - cryptotrading-network

volumes:
  sqlserver_data:
  redis_data:

networks:
  cryptotrading-network:
    driver: bridge