using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CryptoTrading.Models
{
    /// <summary>
    /// Runtime state snapshot for bot recovery and monitoring
    /// </summary>
    [Table("TradingBotRuntimeSnapshots")]
    public class TradingBotRuntimeSnapshot
    {
        [Key]
        [Column(TypeName = "bigint unsigned")]
        public ulong Id { get; set; }

        [Required]
        public Guid TradingBotId { get; set; }

        [ForeignKey(nameof(TradingBotId))]
        public TradingBot? TradingBot { get; set; }

        /// <summary>
        /// When this snapshot was captured
        /// </summary>
        [Required]
        [Column(TypeName = "datetime(6)")]
        public DateTime CapturedAt { get; set; }

        /// <summary>
        /// Serialized runtime state (JSON)
        /// </summary>
        [Required]
        [Column(TypeName = "json")]
        public string RuntimeState { get; set; } = "{}";

        /// <summary>
        /// Last signal generated by the strategy
        /// </summary>
        [MaxLength(500)]
        public string? LastSignal { get; set; }

        /// <summary>
        /// Summary of open positions (JSON)
        /// </summary>
        [Column(TypeName = "json")]
        public string? OpenPositionSummary { get; set; }

        /// <summary>
        /// Next scheduled tick time
        /// </summary>
        [Column(TypeName = "datetime(6)")]
        public DateTime? NextTickAt { get; set; }

        /// <summary>
        /// Version for optimistic concurrency control
        /// </summary>
        [ConcurrencyCheck]
        [Column(TypeName = "datetime(6)")]
        public DateTime? Version { get; set; }
    }
}

